# Generated by Django 3.1.6 on 2021-04-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftapp', '0003_auto_20210324_0223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='main',
        ),
        migrations.AddField(
            model_name='product',
            name='categorie',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
